fos_rest:
  view:
    formats: { json : true, xml : false, rss: false, text: false }
    view_response_listener:  true
  serializer :
    serialize_null: true
  body_converter :
    enabled: true
  format_listener:
    rules:
      - { path: ^/, prefer_extension: true, fallback_format: json, priorities: [ json ] }